import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import WithSubnavigation from '@/components/navbar'
import CallToActionWithAnnotation from '@/components/hero'
import WithSpeechBubbles from '@/components/review'
import LargeWithLogoLeft from '@/components/footer'
import { GetServerSideProps, NextPageContext } from 'next'
import Success from '@/components/Success'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props : any) {
    console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithSubnavigation/>
      <main>
        <Success title={props.data.toto} />
      </main>
    </>
  )
}


   
// This gets called on every request
export async function getServerSideProps(context: NextPageContext) {
    const data = context.query

    return { props: { data } }
}
