import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import WithSubnavigation from '@/components/navbar'
import CallToActionWithAnnotation from '@/components/hero'
import SimpleThreeColumns from '@/components/feature'
import WithSpeechBubbles from '@/components/review'
import LargeWithLogoLeft from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithSubnavigation/>
      <main>
        <CallToActionWithAnnotation/>
        <SimpleThreeColumns/>
        <WithSpeechBubbles/>
        <LargeWithLogoLeft/>
      </main>
    </>
  )
}
